export const PUBLIC_ROUTES = [
  "/",
  "/login",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/api/auth/login",
  "/api/health",
] as const;

export const AUTH_ROUTES = [
  "/login",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
] as const;

export const PROTECTED_ROUTE_PREFIXES = [
  "/dashboard",
  "/ai-copilot",
  "/war-room",
  "/skills",
  "/skill-matrix",
  "/learning",
  "/course",
  "/courses",
  "/assessments",
  "/certifications",
  "/analytics",
  "/reports",
  "/talent",
  "/succession",
  "/forecasting",
  "/workforce-forecasting",
  "/executive-war-room",
  "/executive-intelligence",
  "/executive-analytics",
  "/department-analytics",
  "/team-analytics",
  "/compliance-analytics",
  "/contractors",
  "/teams",
  "/departments",
  "/skill-framework",
  "/competency-models",
  "/skill-validation",
  "/learning-programs",
  "/career",
  "/career-progression",
  "/goals",
  "/succession-planning",
  "/employees",
  "/admin",
  "/admin/people",
  "/settings",
  "/account",
  "/api",
] as const;

export const API_PUBLIC_ROUTES = [
  "/api/auth/login",
  "/api/auth/logout",
  "/api/auth/refresh",
  "/api/auth/forgot-password",
  "/api/auth/reset-password",
  "/api/auth/verify-email",
  "/api/auth/resend-verification",
  "/api/auth/sso",
  "/api/auth/sso/config",
  "/api/health",
  "/api/csrf",
  "/api/certificates/verify",
] as const;

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  DASHBOARD: "/dashboard",
  SETTINGS: "/settings",
  SETTINGS_SECURITY: "/settings/security",
  SKILLS: "/skills",
  SKILL_MATRIX: "/analytics",
  LEARNING: "/learning",
  LEARNING_OPEN_COURSES: "/learning?tab=learning-content",
  openCoursePlayer: (courseId: string) => `/learning/open-courses/${courseId}`,
  coursePlayer: (courseId: string) => `/courses/${courseId}`,
  COURSES: "/courses",
  ASSESSMENTS: "/assessments",
  assessmentTake: (assessmentId: string, options?: { courseId?: string; moduleId?: string }) => {
    const params = new URLSearchParams({ tab: "take", assessmentId });
    if (options?.courseId) params.set("courseId", options.courseId);
    if (options?.moduleId) params.set("moduleId", options.moduleId);
    return `/assessments?${params.toString()}`;
  },
  CERTIFICATIONS: "/certifications",
  ANALYTICS: "/analytics",
  REPORTS: "/reports",
  TALENT: "/talent",
  SUCCESSION: "/succession",
  FORECASTING: "/forecasting",
  ADMIN: "/admin",
  adminLearningAssignment: (id: string) => `/admin/learning/assignments/${id}`,
  ADMIN_ROLES: "/admin/roles",
  ADMIN_USERS: "/admin/people?tab=users",
  ADMIN_ORGANIZATION: "/admin/people?tab=organization",
  adminUser: (userId: string) => `/admin/users/${userId}`,
  ADMIN_DEPARTMENTS: "/admin/people?tab=organization",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
  EMPLOYEES: "/employees",
  FORBIDDEN: "/forbidden",
  ACCOUNT: "/account",
} as const;
