"use client";

import { useEffect, useRef, useState } from "react";
import { ClipboardCheck, Loader2, Sparkles } from "lucide-react";
import { useAssessmentMutations } from "@/hooks/use-assessments";
import { useGenerateCourseQuiz } from "@/hooks/use-learning-roadmap";
import type { RoadmapLevelStep } from "@/types/learning-roadmap";
import type { AttemptResult, AttemptSession } from "@/types/assessments";
import { AssessmentTaker, AttemptResultView } from "@/components/assessments/assessment-taker";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface RoadmapAssessmentActionProps {
  step: RoadmapLevelStep;
  onComplete?: () => void;
}

export function RoadmapAssessmentAction({ step, onComplete }: RoadmapAssessmentActionProps) {
  const generateQuiz = useGenerateCourseQuiz();
  const mutations = useAssessmentMutations();
  const [session, setSession] = useState<AttemptSession | null>(null);
  const [result, setResult] = useState<AttemptResult | null>(null);
  const autoGenerated = useRef(false);

  const courseDone = step.progress.courseStatus === "COMPLETED";
  const assessment = step.assessment;
  const hasStructuredModules = (step.course?.moduleCount ?? 0) > 0;

  useEffect(() => {
    if (!courseDone || !assessment || assessment.quizReady || autoGenerated.current || !step.course) {
      return;
    }
    autoGenerated.current = true;
    generateQuiz.mutate(step.course.id, {
      onSuccess: () => onComplete?.(),
    });
  }, [assessment, courseDone, generateQuiz, onComplete, step.course]);
  if (hasStructuredModules || !courseDone || !assessment) return null;

  const quizReady = assessment.quizReady;
  const assessmentPassed = step.progress.assessmentPassed === true;
  const assessmentFailed = step.progress.assessmentPassed === false;

  async function handleGenerateQuiz() {
    if (!step.course) return;
    await generateQuiz.mutateAsync(step.course.id);
    onComplete?.();
  }

  async function handleStartAssessment() {
    const nextSession = await mutations.startAttempt.mutateAsync(assessment!.id);
    setSession(nextSession);
    setResult(null);
  }

  function handleAssessmentComplete(nextResult: AttemptResult) {
    setResult(nextResult);
    setSession(null);
    onComplete?.();
  }

  if (assessmentPassed) return null;

  return (
    <>
      <div className="mt-3 flex flex-wrap gap-2">
        {!quizReady ? (
          <Button
            size="sm"
            variant="secondary"
            disabled={generateQuiz.isPending}
            onClick={handleGenerateQuiz}
          >
            {generateQuiz.isPending ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Generating quiz…
              </>
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5" />
                Generate syllabus quiz
              </>
            )}
          </Button>
        ) : (
          <Button size="sm" disabled={mutations.startAttempt.isPending} onClick={handleStartAssessment}>
            {mutations.startAttempt.isPending ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Starting…
              </>
            ) : (
              <>
                <ClipboardCheck className="h-3.5 w-3.5" />
                {assessmentFailed ? "Retake level assessment" : "Take level assessment"}
              </>
            )}
          </Button>
        )}
      </div>

      {assessmentFailed && step.progress.assessmentScore !== null && (
        <p className="mt-2 text-xs text-destructive">
          Score {step.progress.assessmentScore}% — minimum {assessment.passingScore}% required. Retake
          to continue.
        </p>
      )}

      <Dialog open={!!session || !!result} onOpenChange={() => { setSession(null); setResult(null); }}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>{assessment.title}</DialogTitle>
          </DialogHeader>
          {session && (
            <AssessmentTaker
              session={session}
              onClose={() => setSession(null)}
              onComplete={handleAssessmentComplete}
            />
          )}
          {result && (
            <AttemptResultView
              result={result}
              onClose={() => setResult(null)}
              onRetake={
                !result.passed && result.canRetake
                  ? () => {
                      setResult(null);
                      handleStartAssessment();
                    }
                  : undefined
              }
            />
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
